### ISSUE TITLE
Error adding assertions

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-vlrc#19]
On the gooru server, I'm trying to make self-assertions in the VLRC but the boxes won't check. The console is displaying this message:

![gooru-vlrc](https://user-images.githubusercontent.com/33300923/51403679-2b8b5b00-1b1f-11e9-833b-8a6f29fd0c46.PNG)

When I go to the Profile after, the assertion from the VLRC has saved.

**Comment by Lomilar** [comment]
Likely solved by upgrading.

**Comment by woodkri** [comment]
You're right! Upgraded and closing issue.
